version: "3"
services:
  psql-db:
    image: postgres:16
    container_name: psql-db
    ports:
    - "5432:5432"
    
    environment:
      - POSTGRES_USER=covid-db
      - POSTGRES_PASSWORD=covid-db
      - POSTGRES_DB=covid-db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U covid-db"]
      interval: 10s
      timeout: 5s
      retries: 5
      
    restart: always


  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    depends_on:
      psql-db:
        condition: service_healthy